const VideoComponentItems =[
    {
        image:"https://img.youtube.com/vi/ykMHDKB0-1o/maxresdefault.jpg",
        subs:"500 K",
        views:"1.4 M",
        description:"Do you want a FREE one hour training... Visit our our page imediately!!!",
        timestamp:"1 hour ago",
        channel:"Travis Scott",
        title:"TYLER1: TWITCH RIVALS GLITCH CON EDITION",
        scaleComponent: true,
    },
    {
        image:"https://img.youtube.com/vi/ykMHDKB0-1o/maxresdefault.jpg",
        subs:"500 K",
        views:"1.4 M",
        description:"Do you want a FREE one hour training... Visit our our page imediately!!!",
        timestamp:"1 hour ago",
        channel:"Travis Scott",
        title:"Travis Scott - YOSEMITE (Audio)",
        scaleComponent:true,
    },
    {
        image:"https://img.youtube.com/vi/ykMHDKB0-1o/maxresdefault.jpg",
        subs:"500 K",
        views:"1.4 M",
        description:"Do you want a FREE one hour training... Visit our our page imediately!!!",
        timestamp:"1 hour ago",
        channel:"Travis Scott",
        title:"Travis Scott - YOSEMITE (Audio)",
        scaleComponent:true,
    },{
        image:"https://img.youtube.com/vi/ykMHDKB0-1o/maxresdefault.jpg",
        subs:"500 K",
        views:"1.4 M",
        description:"Do you want a FREE one hour training... Visit our our page imediately!!!",
        timestamp:"1 hour ago",
        channel:"Travis Scott",
        title:"Travis Scott - YOSEMITE (Audio)",
        scaleComponent:true,
    },{
        image:"https://img.youtube.com/vi/ykMHDKB0-1o/maxresdefault.jpg",
        subs:"500 K",
        views:"1.4 M",
        description:"Do you want a FREE one hour training... Visit our our page imediately!!!",
        timestamp:"1 hour ago",
        channel:"Travis Scott",
        title:"Travis Scott - YOSEMITE (Audio)",
        scaleComponent:true,
    },{
        image:"https://img.youtube.com/vi/ykMHDKB0-1o/maxresdefault.jpg",
        subs:"500 K",
        views:"1.4 M",
        description:"Do you want a FREE one hour training... Visit our our page imediately!!!",
        timestamp:"1 hour ago",
        channel:"Travis Scott",
        title:"Travis Scott - YOSEMITE (Audio)",
        scaleComponent:true,
    },{
        image:"https://img.youtube.com/vi/ykMHDKB0-1o/maxresdefault.jpg",
        subs:"500 K",
        views:"1.4 M",
        description:"Do you want a FREE one hour training... Visit our our page imediately!!!",
        timestamp:"1 hour ago",
        channel:"Travis Scott",
        title:"Travis Scott - YOSEMITE (Audio)",
        scaleComponent:true,
    },{
        image:"https://img.youtube.com/vi/ykMHDKB0-1o/maxresdefault.jpg",
        subs:"500 K",
        views:"1.4 M",
        description:"Do you want a FREE one hour training... Visit our our page imediately!!!",
        timestamp:"1 hour ago",
        channel:"Travis Scott",
        title:"Travis Scott - YOSEMITE (Audio)",
        scaleComponent:true,
    },{
        image:"https://img.youtube.com/vi/ykMHDKB0-1o/maxresdefault.jpg",
        subs:"500 K",
        views:"1.4 M",
        description:"Do you want a FREE one hour training... Visit our our page imediately!!!",
        timestamp:"1 hour ago",
        channel:"Travis Scott",
        title:"Travis Scott - YOSEMITE (Audio)",
        scaleComponent:true,
    },{
        image:"https://img.youtube.com/vi/ykMHDKB0-1o/maxresdefault.jpg",
        subs:"500 K",
        views:"1.4 M",
        description:"Do you want a FREE one hour training... Visit our our page imediately!!!",
        timestamp:"1 hour ago",
        channel:"Travis Scott",
        title:"Travis Scott - YOSEMITE (Audio)",
        scaleComponent:true,
    },{
        image:"https://img.youtube.com/vi/ykMHDKB0-1o/maxresdefault.jpg",
        subs:"500 K",
        views:"1.4 M",
        description:"Do you want a FREE one hour training... Visit our our page imediately!!!",
        timestamp:"1 hour ago",
        channel:"Travis Scott",
        title:"Travis Scott - YOSEMITE (Audio)",
        scaleComponent:true,
    },{
        image:"https://img.youtube.com/vi/ykMHDKB0-1o/maxresdefault.jpg",
        subs:"500 K",
        views:"1.4 M",
        description:"Do you want a FREE one hour training... Visit our our page imediately!!!",
        timestamp:"1 hour ago",
        channel:"Travis Scott",
        title:"Travis Scott - YOSEMITE (Audio)",
        scaleComponent:true,
    },{
        image:"https://img.youtube.com/vi/ykMHDKB0-1o/maxresdefault.jpg",
        subs:"500 K",
        views:"1.4 M",
        description:"Do you want a FREE one hour training... Visit our our page imediately!!!",
        timestamp:"1 hour ago",
        channel:"Travis Scott",
        title:"Travis Scott - YOSEMITE (Audio)",
        scaleComponent:true,
    },{
        image:"https://img.youtube.com/vi/ykMHDKB0-1o/maxresdefault.jpg",
        subs:"500 K",
        views:"1.4 M",
        description:"Do you want a FREE one hour training... Visit our our page imediately!!!",
        timestamp:"1 hour ago",
        channel:"Travis Scott",
        title:"Travis Scott - YOSEMITE (Audio)",
        scaleComponent:true,
    },{
        image:"https://img.youtube.com/vi/ykMHDKB0-1o/maxresdefault.jpg",
        subs:"500 K",
        views:"1.4 M",
        description:"Do you want a FREE one hour training... Visit our our page imediately!!!",
        timestamp:"1 hour ago",
        channel:"Travis Scott",
        title:"Travis Scott - YOSEMITE (Audio)",
        scaleComponent:true,
    },{
        image:"https://img.youtube.com/vi/ykMHDKB0-1o/maxresdefault.jpg",
        subs:"500 K",
        views:"1.4 M",
        description:"Do you want a FREE one hour training... Visit our our page imediately!!!",
        timestamp:"1 hour ago",
        channel:"Travis Scott",
        title:"Travis Scott - YOSEMITE (Audio)",
        scaleComponent:true,
    },{
        image:"https://img.youtube.com/vi/ykMHDKB0-1o/maxresdefault.jpg",
        subs:"500 K",
        views:"1.4 M",
        description:"Do you want a FREE one hour training... Visit our our page imediately!!!",
        timestamp:"1 hour ago",
        channel:"Travis Scott",
        title:"Travis Scott - YOSEMITE (Audio)",
        scaleComponent:true,
    },{
        image:"https://img.youtube.com/vi/ykMHDKB0-1o/maxresdefault.jpg",
        subs:"500 K",
        views:"1.4 M",
        description:"Do you want a FREE one hour training... Visit our our page imediately!!!",
        timestamp:"1 hour ago",
        channel:"Travis Scott",
        title:"Travis Scott - YOSEMITE (Audio)",
        scaleComponent:true,
    },{
        image:"https://img.youtube.com/vi/ykMHDKB0-1o/maxresdefault.jpg",
        subs:"500 K",
        views:"1.4 M",
        description:"Do you want a FREE one hour training... Visit our our page imediately!!!",
        timestamp:"1 hour ago",
        channel:"Travis Scott",
        title:"Travis Scott - YOSEMITE (Audio)",
        scaleComponent:true,
    },{
        image:"https://img.youtube.com/vi/ykMHDKB0-1o/maxresdefault.jpg",
        subs:"500 K",
        views:"1.4 M",
        description:"Do you want a FREE one hour training... Visit our our page imediately!!!",
        timestamp:"1 hour ago",
        channel:"Travis Scott",
        title:"Travis Scott - YOSEMITE (Audio)",
        scaleComponent:true,
    },{
        image:"https://img.youtube.com/vi/ykMHDKB0-1o/maxresdefault.jpg",
        subs:"500 K",
        views:"1.4 M",
        description:"Do you want a FREE one hour training... Visit our our page imediately!!!",
        timestamp:"1 hour ago",
        channel:"Travis Scott",
        title:"Travis Scott - YOSEMITE (Audio)",
        scaleComponent:true,
    },{
        image:"https://img.youtube.com/vi/ykMHDKB0-1o/maxresdefault.jpg",
        subs:"500 K",
        views:"1.4 M",
        description:"Do you want a FREE one hour training... Visit our our page imediately!!!",
        timestamp:"1 hour ago",
        channel:"Travis Scott",
        title:"Travis Scott - YOSEMITE (Audio)",
        scaleComponent:true,
    },{
        image:"https://img.youtube.com/vi/ykMHDKB0-1o/maxresdefault.jpg",
        subs:"500 K",
        views:"1.4 M",
        description:"Do you want a FREE one hour training... Visit our our page imediately!!!",
        timestamp:"1 hour ago",
        channel:"Travis Scott",
        title:"Travis Scott - YOSEMITE (Audio)",
        scaleComponent:true,
    },
]

export default VideoComponentItems;